### ISSUE TITLE
Tech debt tracking

### ISSUE THREAD

**Issue by JasonAlt** [globus/globus-ssh#4]
Tracking status of the client-side implementation of SSH with Globus Auth

- [ ] Exit on unknown user (actually, never re display the token prompt)
- [ ] Support 'logout -all' ??
- [ ] sftp support
- [ ] CLI-like hidden venv
- [ ] "Easy" updates
- [ ] Auto popup browser during consent flow when possible
- [x] Unit Tests
- [ ] Don't refresh the access token if not needed
- [ ] Fix 'invalid grant' message when refresh token is bogus
- [x] Python 3.x support

**Comment by aaschaer** [comment]
A couple questions:

* For sftp support, is there something preventing us from using `sftp -S globus-ssh`?

* are "Easy" updates supposed to be something like the cli's `globus update`?

**Comment by JasonAlt** [comment]
For sftp support, I'd prefer globus-sftp for consistency with globus-ssh / globus-scp. And yeah, 'easy updates' are meant to mimic the CLI's behavior of 'globus update'.

**Comment by JasonAlt** [comment]
These items have been split out into separate tracking issues.
